version: '2.4'
services:
  agent:
    build:
      context: .
    volumes:
      - ./agentmodel:/model
    image: kulhanek/visual-navigation-agent-pytorch

  train:
    ipc: host
    runtime: nvidia
    command: "python -u /app/train.py --num_thread 5"
    image: kulhanek/visual-navigation-agent-pytorch
    volumes:
      - ./agentmodel:/model
      - ./runs:/app/runs
    environment:
      - PYTHONUNBUFFERED=1 
      - OMP_NUM_THREADS=1
    depends_on:
      - agent
  eval:
    ipc: host
    runtime: nvidia
    command: "python -u /app/eval.py"
    image: kulhanek/visual-navigation-agent-pytorch
    volumes:
      - ./agentmodel:/model
    environment:
      - PYTHONUNBUFFERED=1 
      - OMP_NUM_THREADS=1
    depends_on:
      - agent

  train_restore:
    ipc: host
    runtime: nvidia
    image: kulhanek/visual-navigation-agent-pytorch
    volumes:
      - ./agentmodel:/model
    environment:
      - PYTHONUNBUFFERED=1 
      - OMP_NUM_THREADS=1
    depends_on:
      - agent
    command: "python -u /app/train.py --restore"

  bash:
    command: 'bash'
    runtime: nvidia
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    depends_on:
      - agent
    environment:
      - DISPLAY=${DISPLAY}
    image: kulhanek/visual-navigation-agent-pytorch
