version: '2.4'
services:
  agent:
    build:
      context: .
    image: norips/visual-navigation-agent-pytorch

  train:
    ipc: host
    runtime: nvidia
    command: "python -u /app/train.py -e /exp/$EXPERIMENT/param.json"
    image: norips/visual-navigation-agent-pytorch
    volumes:
      - ./EXPERIMENTS:/exp
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1 
      - OMP_NUM_THREADS=1
    depends_on:
      - agent

  train_resnet:
    ipc: host
    runtime: nvidia
    command: "python -u /app/train.py -e /exp/$EXPERIMENT/param.json"
    image: norips/visual-navigation-agent-pytorch
    volumes:
      - ./EXPERIMENTS:/exp
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1 
      - OMP_NUM_THREADS=1
    depends_on:
      - agent

  eval:
    ipc: host
    runtime: nvidia
    command: "python -u /app/eval.py -e /exp/$EXPERIMENT/param.json"
    image: norips/visual-navigation-agent-pytorch
    volumes:
      - ./EXPERIMENTS:/exp
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1 
      - OMP_NUM_THREADS=1
    depends_on:
      - agent

  train_restore:
    ipc: host
    runtime: nvidia
    command: "python -u /app/train.py -e /exp/$EXPERIMENT/param.json --restore"
    image: norips/visual-navigation-agent-pytorch
    volumes:
      - ./EXPERIMENTS:/exp
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1 
      - OMP_NUM_THREADS=1
    depends_on:
      - agent
  bash:
    command: 'bash'
    runtime: nvidia
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    depends_on:
      - agent
    volumes:
      - ./EXPERIMENTS:/app/EXPERIMENTS
    environment:
      - DISPLAY=${DISPLAY}
    image: norips/visual-navigation-agent-pytorch
